apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-check
  labels:
    app: email-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-check
  template:
    metadata:
      labels:
        app: email-check
    spec:
      containers:
        - name: email-check
          image: akash2061/email-check:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: email-check-service
  labels:
    app: email-check
spec:
  selector:
    app: email-check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: email-check-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-check
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20 #!Testing
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
