---
- name: Deploy to K3s
  hosts: k3s_servers
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    # ? To improve time efficiency, don't clone entire repo. Just curl the k8s.yml file.
    - name: Pull latest code from GitHub
      ansible.builtin.git:
        repo: https://github.com/akash2061/K8s-Project.git
        dest: /root/K8s-Project
        force: true
        version: main

    # - name: Delete existing deployment (if exists)
    #   ansible.builtin.shell: |
    #     kubectl delete deployment email-check --ignore-not-found=true --force
    #   changed_when: true

    # - name: Delete existing service (if exists)
    #   ansible.builtin.shell: |
    #     kubectl delete service email-check-service --ignore-not-found=true --force
    #   changed_when: true

    # - name: Delete existing HPA (if exists)
    #   ansible.builtin.shell: |
    #     kubectl delete hpa email-check-hpa --ignore-not-found=true --force
    #   changed_when: true

    - name: Apply Kubernetes manifests (rolling update)
      ansible.builtin.shell: |
        kubectl apply -f /root/K8s-Project/k8s/k8s.yml
      changed_when: true

    - name: Force rolling update to pull latest image
      ansible.builtin.shell: |
        kubectl rollout restart deployment/email-check
      changed_when: true

    - name: Wait for rollout to complete
      ansible.builtin.shell: |
        kubectl rollout status deployment/email-check --timeout=300s
      changed_when: false

    - name: Wait for pods to be running
      ansible.builtin.shell: |
        kubectl wait --for=condition=ready pod -l app=email-check --timeout=120s
      changed_when: false

    - name: Check deployment status
      ansible.builtin.command: kubectl get pods -l app=email-check
      register: pod_status
      changed_when: false

    - name: Show deployment status
      ansible.builtin.debug:
        msg: "{{ pod_status.stdout }}"

    - name: Wait for HPA to stabilize
      ansible.builtin.pause:
        seconds: 60
        prompt: "Waiting for HPA metrics to initialize..."

    - name: Check HPA status
      ansible.builtin.command: kubectl get hpa
      register: hpa_status
      changed_when: false

    - name: Show HPA status
      ansible.builtin.debug:
        msg: "{{ hpa_status.stdout }}"

    - name: Get service information
      ansible.builtin.command: kubectl get svc email-check-service
      register: service_status
      changed_when: false

    - name: Show service status
      ansible.builtin.debug:
        msg: "{{ service_status.stdout }}"
